# Generated by Django 5.0.1 on 2025-06-06 08:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('THINGS_TO_DO', 'Things to Do'), ('FOOD_DRINK', 'Food & Drink'), ('ART_CULTURE', 'Art & Culture'), ('THEATRE_FILMS', 'Theatre & Films')], default='THINGS_TO_DO', max_length=20)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of attendees')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time'],
                'indexes': [models.Index(fields=['status', 'date_time'], name='events_even_status_8b865d_idx'), models.Index(fields=['category'], name='events_even_categor_aca11d_idx'), models.Index(fields=['owner'], name='events_even_owner_i_52e16c_idx')],
            },
        ),
    ]
